package xktz.game.effect;

public enum TargetType {
    ALL,
    ALL_ENEMY,
    ALL_ALLIANCE,
    ONE_ENEMY,
    ONE_ALLIANCE,
    ONE_SOLDIER,
    ENEMY_HEADQUARTER,
    ALLIANCE_HEADQUARTER,
    DRAW_CARD,
    LOSE_CARD,
    BACK_CARD,
    GAIN_CARD,
    ADD_CARD_TO_ALLIANCE_BATTLEFIELD,
    ADD_CARD_TO_ENEMY_BATTLEFIELD
}
